// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Menggunakan variabel lingkungan dari .env
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Extract project ID from SUPABASE_URL
const SUPABASE_PROJECT_ID = SUPABASE_URL.split('//')[1].split('.')[0];

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export { SUPABASE_PROJECT_ID };