// This file is automatically generated. Do not edit it directly.
        import { createClient } from '@supabase/supabase-js';

        // Menggunakan variabel lingkungan dari .env
        const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
        const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

        // Log untuk debugging: Pastikan kunci API dimuat dengan benar
        // console.log("Supabase Client Init: VITE_SUPABASE_URL:", SUPABASE_URL ? "Loaded" : "NOT LOADED");
        // console.log("Supabase Client Init: VITE_SUPABASE_ANON_KEY:", SUPABASE_PUBLISHABLE_KEY ? "Loaded" : "NOT LOADED");

        // Extract project ID from SUPABASE_URL (if URL exists)
        const SUPABASE_PROJECT_ID = SUPABASE_URL ? SUPABASE_URL.split('//')[1].split('.')[0] : 'UNKNOWN';

        // console.log("Supabase Client Init: Project ID:", SUPABASE_PROJECT_ID);
        // console.log("Supabase Client: Actual URL used:", SUPABASE_URL);
        // console.log("Supabase Client: Actual Anon Key used (first 5 chars):", SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.substring(0, 5) + '...' : 'N/A');

        // Import the supabase client like this:
        // import { supabase } from "@/integrations/supabase/client";

        // Create client only if both URL and key are available to avoid runtime errors
        export const supabase = createClient(
          SUPABASE_URL || 'http://localhost', // Provide a fallback to prevent client creation error if undefined
          SUPABASE_PUBLISHABLE_KEY || 'dummy_key' // Provide a fallback
        );
        export { SUPABASE_PROJECT_ID };